# TEMPLATED
version: 2.1
workflows:
  version: 2
  test:
    jobs:
    - submit-daffy-stage:
        context: pip-staging
        filters:
          branches:
            only: /daffy-staging.*/
    - submit-daffy-prod:
        context: production
        filters:
          branches:
            ignore: /daffy-staging.*/
jobs:
  submit: &template
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
    - checkout

    - run:
        name: Install deps
        # language=bash
        command: |
          python3 -m pip install -U pip
          python3 -m pip install duckietown-shell
    - run:
        name: Python stats
        command: |
          mkdir -p build-stats
          env | sort | tee  build-stats/env.txt

          python3 -m pip list | sort | tee  build-stats/pip-list.txt
          python3 -m pip freeze | sort | tee  build-stats/pip-freeze.txt
    - store_artifacts:
        path: build-stats
        destination: build-stats

    - run:
        name: Setup daffy commands
        # language=bash
        command: |
          set -x
          dts --set-version "$DTS_VERSION"
          dts update
    - run:
        name: Setup token
        # language=bash
        command: |
          set -x
          dts tok verify "${token_dt1_bea}"
          dts tok set "${token_dt1_bea}"
          pip install shyaml
          # this does not matter on the staging server
          dts challenges config --docker-server "$DOCKER_REGISTRY" --docker-username "$DOCKER_USERNAME" --docker-password "$DOCKER_PASSWORD"
          dts challenges config --docker-server registry-stage.duckietown.org --docker-username "$DOCKER_USERNAME" --docker-password "$DOCKER_PASSWORD"
    - run:
        name: "Challenges info"
        # language=bash
        command: |
          dts challenges info

    - run:
        name: Submit
        # language=bash
        command: |
          set -x
          #dts challenges evaluate --challenge aido-hello-sim-validation
          name="$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH:$CIRCLE_SHA1"
          validation_challenge=$(shyaml get-value validation_challenge < submission.yaml)
          dts challenges submit --impersonate 1639 --challenge "$validation_challenge" --user-label "${name}"
          dts challenges follow --label "${name}" --exit-when-complete

  submit-daffy-prod: *template
  submit-daffy-stage: *template
#
